name: Build Debug APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: '0'

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant gradlew permission
        working-directory: V2rayNG
        run: chmod +x ./gradlew

      - name: Build debug APK
        working-directory: V2rayNG
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: departament-debug-apk
          path: V2rayNG/app/build/outputs/apk/**/*.apk
